<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.openhab.osgiify</groupId>
    <artifactId>org.openhab.reactor.osgiify</artifactId>
    <version>1.0.0</version>
  </parent>

  <artifactId>com.hubspot.jinjava.jinjava</artifactId>
  <version>2.8.3</version>

  <name>Jinjava</name>

  <properties>
    <origin.groupId>com.hubspot.jinjava</origin.groupId>
    <origin.artifactId>jinjava</origin.artifactId>
    <origin.version>2.8.3</origin.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.hubspot</groupId>
      <artifactId>algebra</artifactId>
      <version>1.7.2</version>
      <exclusions>
        <!-- Don't include Jackson dependencies in the bundle jar; we'll use openHAB's versions of Jackson bundle -->
        <exclusion>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-databind</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-annotations</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
  </dependencies>

</project>
